# Dependencies
markdown: redcarpet
pygments: true

redcarpet:
  extensions: ['smart']

# Permalinks
permalink: pretty

# Setup
title: Playbook
tagline: 'How we work and make things at GPMD'
description: 'This site outlines how we operate as a company'
baseurl: http://gpmd.github.io/playbook

author:
  name: 'Matt Bailey'
  url: https://twitter.com/_mattbailey

# Pagination
#paginate: 1

# Exclusions
exclude: ['*.sublime-project','*.sublime-workspace']

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/gpmd/playbook

# prose.io config
prose:
  siteurl: 'http://gpmd.github.io/playbook/'
  relativeLinks: 'http://gpmd.github.io/playbook/links.jsonp'
  media: 'assets/uploads'
  ignore:
    - /_includes/footer.html
    - /_includes/head.html
    - /_includes/masthead.html
    - /_includes/nav.html
    - /_layouts
    - /_site
    - /assets
    - .gitignore
    - 404.html
    - _config.yml
    - atom.xml
    - links.jsonp
    - README.md
  metadata:
    _posts:
      - name: 'category'
        field:
          element: 'hidden'
          value: 'blog'
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'blog'
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
          value: ''
    _posts/pages:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'page'
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
          value: ''
      - name: 'permalink'
        field:
          element: 'text'
          label: 'Permalink'
          value: ''