# Dependencies
markdown:       redcarpet
pygments:       true

# Permalinks
permalink:      pretty

# Setup
title:          Colophon
tagline:        'How we work and make things at GPMD'
description:    'This site outlines how we operate as a company'
baseurl:        http://gpmd.github.io/colophon

author:
  name:         'Matt Bailey'
  url:          https://twitter.com/_mattbailey

#paginate:      1

# Exclusions
exclude:        ['*.sublime-project','*.sublime-workspace']

# Custom vars
version:        1.0.0

github:
  repo:         https://github.com/gpmd/colophon

# prose.io config
prose:
  rooturl: '_posts'
  siteurl: 'http://gpmd.github.io/colophon/'
  media: 'assets/uploads'
  metadata:
    _posts/static:
      - name: 'Layout'
        field:
          element: 'hidden'
          value: 'page'
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
          value: ''
      - name: 'permalink'
        field:
          element: 'text'
          label: 'Permalink'
          value: ''